version: '3.8'

services:
  user:
    image: ${ECR_REGISTRY}/vybz-user:latest
    container_name: vybz-user-staging
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - BASE_URL=${STAGING_BASE_URL}
      - BASE_API_URL=${STAGING_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${STAGING_NEXTAUTH_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  busker:
    image: ${ECR_REGISTRY}/vybz-busker:latest
    container_name: vybz-busker-staging
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=staging
      - BASE_URL=${STAGING_BASE_URL}
      - BASE_API_URL=${STAGING_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${STAGING_NEXTAUTH_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin:
    image: ${ECR_REGISTRY}/vybz-admin:latest
    container_name: vybz-admin-staging
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=staging
      - BASE_URL=${STAGING_BASE_URL}
      - BASE_API_URL=${STAGING_API_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${STAGING_NEXTAUTH_URL}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: vybz-nginx-staging
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - user
      - busker
      - admin
    restart: unless-stopped 