name: Deployment Notifications

on:
  workflow_run:
    workflows: ["Deploy to Staging", "Deploy to Production"]
    types:
      - completed

jobs:
  notify:
    name: Send Notification
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    
    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ github.event.workflow_run.conclusion }}
          channel: '#deployments'
          text: |
            Deployment ${{ github.event.workflow_run.conclusion }}!
            Workflow: ${{ github.event.workflow_run.name }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            Commit: ${{ github.event.workflow_run.head_sha }}
            URL: ${{ github.event.workflow_run.html_url }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Notify Discord
        if: github.event.workflow_run.conclusion == 'failure'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ github.event.workflow_run.conclusion }}
          title: "Deployment Failed"
          description: |
            Workflow: ${{ github.event.workflow_run.name }}
            Branch: ${{ github.event.workflow_run.head_branch }}
            [View Details](${{ github.event.workflow_run.html_url }}) 